### PR TITLE
Feature/vue3

### PR DESCRIPTION
**Pull request by Botz**
This PR adds basic support for Vue3
#123

### CODE REVIEW

**Comment by lavrton** [comment]
That is a very good Pull Request.

It will not work with `vue@2`, right?

**Comment by Botz** [comment]
Thx, yeah it will not work with vue2...

**Comment by lavrton** [comment]
@Botz can you also take a look into tests? Are there any simple way to fix them to just enable `npm run test` again?

**Comment by Botz** [comment]
@lavrton yes of course...

**Comment by Botz** [comment]
@lavrton
I managed to get the tests running. But i had to disable a few tests. Because there is a API change in vue and i can't access the child components with the related konvaNode to update the zIndex in `checkOrder()`

Maybe you can have a look and find another way?

This function was a little bit confusing for me at first, so maybe we can discuss if it is really necessary?! 
Because, if i got it right, the zIndex which i define in an item gets overwritten by this function thats not what i would expect.

**Comment by nohns** [comment]
Awesome stuff. I'm looking forward to the see Vue 3 support!

**Comment by cristianvasquez** [comment]
Looking forward to starting using Konva in Vue 3!

**Comment by sinasita** [comment]
Any news on this PR? Will it get merged? Thanks for all your work @lavrton and @Botz!

**Comment by lavrton** [comment]
I am happy to merge it. But the PR needs to be finished. I don't have enough time to dive in right now. But that order issue must be fixed, all tests should pass.

**Comment by lavrton** [comment]
I fixed some tests here: https://github.com/konvajs/vue-konva/tree/Botz-feature/vue3
But still not all.

**Comment by Botz** [comment]
@lavrton thx for your help
I fixed the deep order tests(had to make the findKonvaNode function recursive again),
and fixed the validation tests.

But there is still one failing test: `checking for loop order`
```
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue 
```
Because the render function doesn't really render a Node the `Node.insertBefore()` function failes. I think this is a problem with vue3 internals.

**Comment by Nukron** [comment]
Really looking forward to use Konva with Vue3! Thanks for the amazing work @lavrton and @Botz!
Are there any news?

**Comment by lavrton** [comment]
I am not sure I will be able to finish that issue from my side.

With vue3 I want to change how `vue-konva` works. `vue3` has some new API for custom renders. But I wasn't able to find any good demos, examples.

If someone can help here, it will be extremely useful.
I saw this example: https://github.com/huruji/vuvas, but as I can see it creates a completely new renderer. But what we need is canvas renderer inside DOM renderer (usual vue). I did see any examples of that.

**Comment by h-guliyev** [comment]
Hi as for example you might look at [vugel](https://github.com/Planning-nl/vugel)

Also, they have just released [vue 3.1](https://github.com/vuejs/vue-next/releases/tag/v3.1.0) which has vue2 compatibility api
# Vue 3.1 is release is dedicated to the Migration Build: a build of Vue 3 that offers Vue 2 compatible behavior to help migrating Vue 2 codebases to Vue 3.

This might be just the right time to add vue 3 support

**Comment by wulucxy** [comment]
HI，thanks for the project。How is the progress now？

**Comment by DavidVaness** [comment]
Thank you for the work guys! keep it up 💪🏼 
would love to use this with vue 3

**Comment by jgiovanni** [comment]
Looking forward to this being merged also! initKonva has a debugger statement in it.
``` js
initKonva: function initKonva() {
      debugger;
```

**Comment by boboldehampsink** [comment]
Other than the debugger; mentioned above this seems to work fine. Can we remove this statement from the package to make it usable?

**Comment by lavrton** [comment]
Closing by https://github.com/konvajs/vue-konva/pull/172

**Pull request closed without merging**
