### PR TITLE
Add Typescript types to package

### PR DESCRIPTION
**Pull request by freeqaz**
Just was using this lib and ran into this. Added my shim to my project, but figured I'd contribute back as well.

Note, I definitely didn't put a ton of work into this type declaration. It could probably benefit from somebody who is a contributor taking a few minutes to spec out every component to help aid the type system.

Cheers!

### CODE REVIEW

**Comment by freeqaz** [comment]
@lavrton and @rafaesc as reviewers. Forgot to add and now I can't add you both, seemingly.

**Comment by lavrton** [comment]
Thanks for your contribution. Yeah, better typescript will be better, but we have to start from something.

**Comment by DylanLukes** [comment]
Hello all, I just installed `vue-konva@2.0.9` in a Typescript enabled project and was met with:

```
ERROR in .../Projects/mockdown-ui/src/main.ts
2:22 Could not find a declaration file for module 'vue-konva'. '.../Projects/mockdown-ui/node_modules/vue-konva/umd/vue-konva.js' implicitly has an 'any' type.
  Try `npm install @types/vue-konva` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-konva';`
    1 | import Vue from 'vue';
  > 2 | import VueKonva from 'vue-konva';
      |                      ^
    3 | Vue.use(VueKonva)
Version: typescript 3.6.3, tslint 5.20.0
```

It looks like `index.d.ts` didn't actually make it into the published package.

**Comment by lavrton** [comment]
@DylanLukes thanks for the note. Just added and published a new version.

**Pull request merged**
